# Generated by Django 4.0.1 on 2022-01-28 19:36

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('flag_path', models.ImageField(blank=True, upload_to='static/images/flags/cities')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('flag_path', models.ImageField(blank=True, upload_to='static/images/flags/countries')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('descriprion', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='static/images/logos/orgs')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('descriprion', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='static/images/logos/sports')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('descriprion', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='static/images/logos/series')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medals.org')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('flag_path', models.ImageField(blank=True, upload_to='static/images/flags/regions')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.country')),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('distance', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(upload_to='static/images/medals/')),
                ('photo_second', models.ImageField(blank=True, upload_to='static/images/medals')),
                ('likes', models.IntegerField(default=0)),
                ('added_by', models.CharField(blank=True, default='fatum', max_length=200)),
                ('credentials', models.CharField(blank=True, default='@fa_tum', max_length=200)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='medals.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.country')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medals.org')),
                ('region', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='medals.region')),
                ('series', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='org', chained_model_field='org', null=True, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='medals.series')),
                ('sport', models.ForeignKey(default='Бег', on_delete=django.db.models.deletion.CASCADE, to='medals.sport', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='medals.region'),
        ),
    ]
