# Generated by Django 4.0.1 on 2022-01-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0004_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
