# Generated by Django 4.0.1 on 2022-02-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0006_medal_to_moderate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='name_lower',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
