# Generated by Django 4.0.1 on 2022-02-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0007_medal_name_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal_to_moderate',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medals.profile'),
        ),
    ]
