# Generated by Django 4.0.1 on 2022-01-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_path',
            field=models.ImageField(blank=True, upload_to='static/images/flags/countries'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('flag_path', models.ImageField(blank=True, upload_to='static/images/flags/regions')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.country')),
            ],
        ),
    ]
