# Generated by Django 4.0.1 on 2022-01-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0005_org_series_sport_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='logo',
            field=models.FileField(blank=True, upload_to='static/images/logos/orgs'),
        ),
    ]
