# Generated by Django 4.0.1 on 2022-01-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0006_alter_org_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medals.org'),
        ),
    ]
