# Generated by Django 4.0.1 on 2022-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0008_alter_series_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='logo',
            field=models.FileField(blank=True, upload_to='static/images/logos/sports'),
        ),
    ]
