# Generated by Django 4.0.1 on 2022-01-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0009_alter_sport_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='date',
            field=models.DateField(),
        ),
    ]
