# Generated by Django 4.0.1 on 2022-01-09 20:32

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0010_alter_medal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='country_id',
            field=models.AutoField(default=builtins.id, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
