# Generated by Django 4.0.1 on 2022-01-09 20:33

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0011_remove_country_id_country_country_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
